apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-nodejs
    spec:
      containers:
      - name: example-nodejs
        image: lmmoraes/example
        ports:
        - name: nodejs-port
          containerPort: 8088