apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-nodejs
  name: service-loadbalance
  namespace: default
spec:
  ports:
  - name: ui
    nodePort: 30383
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: example-nodejs
  sessionAffinity: None
  type: LoadBalancer